package com.nexusstore.nexusstore.models;

import jakarta.validation.constraints.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDate;

/**
 * Domain model representing a product in NexusStore.
 * Mapped to the {@code products} table via Spring Data JDBC annotations.
 * Includes Bean Validation constraints for MVC form binding.
 */
@Table("products")
public class ProductModel {

    /** Primary key – auto-generated by MySQL AUTO_INCREMENT. */
    @Id
    @Column("product_id")
    private Integer productId;

    /** Product name. Required. */
    @NotBlank(message = "Product name is required")
    @Column("name")
    private String name;

    /** Detailed description. Required. */
    @NotBlank(message = "Description is required")
    @Column("description")
    private String description;

    /** Selling price. Must be greater than $0.00. */
    @NotNull(message = "Price is required")
    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
    @Column("price")
    private Double price;

    /** Units available in stock. Cannot be negative. */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity cannot be negative")
    @Column("stock_quantity")
    private Integer stockQuantity;

    /** Product category: Electronics, Apparel, or Accessories. Required. */
    @NotBlank(message = "Category is required")
    @Column("category")
    private String category;

    /** Optional URL to the product image. */
    @Column("image_url")
    private String imageUrl;

    /** Date the product was added to the store. Auto-set on creation. */
    @Column("date_added")
    private LocalDate dateAdded;

    // ── Constructors ──────────────────────────────────────────────────────────

    /**
     * Default no-arg constructor required by Spring MVC model binding
     * and Spring Data JDBC row mapping.
     */
    public ProductModel() {
        this.dateAdded = LocalDate.now();
    }

    /**
     * Full constructor for programmatic creation (e.g. seed data).
     *
     * @param productId     unique product ID (null for new records)
     * @param name          product name
     * @param description   product description
     * @param price         product price
     * @param stockQuantity units in stock
     * @param category      product category
     * @param imageUrl      URL to product image
     */
    public ProductModel(Integer productId, String name, String description,
                        Double price, Integer stockQuantity,
                        String category, String imageUrl) {
        this.productId = productId;
        this.name = name;
        this.description = description;
        this.price = price;
        this.stockQuantity = stockQuantity;
        this.category = category;
        this.imageUrl = imageUrl;
        this.dateAdded = LocalDate.now();
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    /** @return the product's unique ID */
    public Integer getProductId() { return productId; }

    /** @param productId the product's unique ID */
    public void setProductId(Integer productId) { this.productId = productId; }

    /** @return the product name */
    public String getName() { return name; }

    /** @param name the product name */
    public void setName(String name) { this.name = name; }

    /** @return the product description */
    public String getDescription() { return description; }

    /** @param description the product description */
    public void setDescription(String description) { this.description = description; }

    /** @return the product price */
    public Double getPrice() { return price; }

    /** @param price the product price */
    public void setPrice(Double price) { this.price = price; }

    /** @return the stock quantity */
    public Integer getStockQuantity() { return stockQuantity; }

    /** @param stockQuantity the stock quantity */
    public void setStockQuantity(Integer stockQuantity) { this.stockQuantity = stockQuantity; }

    /** @return the product category */
    public String getCategory() { return category; }

    /** @param category the product category */
    public void setCategory(String category) { this.category = category; }

    /** @return the image URL */
    public String getImageUrl() { return imageUrl; }

    /** @param imageUrl the image URL */
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }

    /** @return the date the product was added */
    public LocalDate getDateAdded() { return dateAdded; }

    /** @param dateAdded the date added */
    public void setDateAdded(LocalDate dateAdded) { this.dateAdded = dateAdded; }
}
